# Generated by Django 5.0.7 on 2024-07-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_operator_ticket_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_service', 'In Service'), ('served', 'Served')], default='waiting', max_length=20),
        ),
    ]
