# Generated by Django 5.0.7 on 2024-08-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_ticket_duration_ticket_end_time_ticket_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
