# Generated by Django 5.0.7 on 2024-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_ticket_is_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='letter',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
